Basic row filtering
European-XFEL/DAMNIT pull request #362
Opened 2024-12-11 13:23 UTC by tmichela

Implements basic row filtering based on column values, there are more requirements for this feature, bu that's already a big enough diff and does already something useful.

One regression: support for standalone comments is dropped in the main table. I implemented another table to view them for the proposal that have used them.

[damnit-row-filtering.webm](https://github.com/user-attachments/assets/9db8f950-c58f-4b51-b261-fb40abf0f539)

2025-02-07 15:31 UTC, JamesWrigley requested changes
This is more code than I can properly review in one go, but I tested it locally and it works really nicely :tada: One odd thing I noticed is that the comment column can't be filtered categorically? That seems a bit odd because other string columns can be and the comment column is basically a string column.

Also, please either do a squash merge or clean up the commits before merging. I semi-regularly do bisects and git blames and these kind of commits really hinder that :sweat_smile:

2025-02-07 15:31 UTC, JamesWrigley commented on damnit/gui/table.py
> +        hide_action = QAction(icon(FA6S.eye_slash), "Hide column", self)
I'd remove the `hide_action` code if it's not going to be finished in this PR.

2025-02-10 16:33 UTC, tmichela commented
> please either do a squash merge or clean up the commits before merging

I cleaned up the commit history

> I noticed is that the comment column can't be filtered categorically?

Oh, well spotted, I get all `UserRole` data, but the data on the comment column is `EditRole`, I'll add a fix for that.

2025-02-11 14:12 UTC, JamesWrigley approved these changes
LGTM!

2025-02-11 14:25 UTC, tmichela commented
Thanks!

2025-02-11 14:25 UTC, merged