Dialog to select proposal/directory when starting GUI
European-XFEL/DAMNIT pull request #9
Opened 2023-06-21 15:23 UTC by takluyver

![image](https://github.com/European-XFEL/DAMNIT/assets/327925/8a17fcf8-11e6-4a9d-aeef-d8178815e912)

I haven't tried to do any refactoring to take full advantage of this yet.

2023-07-05 09:30 UTC, JamesWrigley requested changes
Things we discussed:
- Adding tests
- Open dialog from menu entry
- Creating a backend from the dialog if one doesn't exist

2023-07-05 09:30 UTC, JamesWrigley commented on damnit/gui/open_dialog.py
> +            return Path(self.proposal_dir, "usr/Shared/amore")
Nitpicking:
```suggestion
            return Path(self.proposal_dir) / "usr/Shared/amore"
```

2023-07-05 16:42 UTC, takluyver commented
Thanks @JamesWrigley for the review. I've made all the changes we discussed now; do you want to take another look overt the latest changes? The main change, other than the tests, is to the code for creating a DAMNIT DB and starting the backend if they don't already exist.

2023-07-06 09:17 UTC, JamesWrigley commented
Hmmm, now I'm getting crashes when testing this on Maxwell and my local machine :thinking: Both with selecting by proposal and directory:
```
(amore) ➜  mid-2832 git:(open-db-dialog) amore-proto gui --no-kafka    
QThread: Destroyed while thread is still running
[1]    3384071 IOT instruction (core dumped)  amore-proto gui --no-kafka
```

2023-07-06 10:09 UTC, takluyver commented
Gah, threads. I saw those errors while running the tests and fixed them there, but then didn't try again with the actual application. I'll take a look.

2023-07-06 12:30 UTC, takluyver commented
OK, I think I've finally got the application, the local tests and the CI all working :sweat_smile: :crossed_fingers: .

2023-07-06 14:44 UTC, JamesWrigley approved these changes
I didn't have quite enough time to test it myself, but I trust you and CI :grin: LGTM!

(P.S. I might also suggest squashing some of the commits before merging, but I leave that up to you)

2023-07-06 15:40 UTC, merged